title: New Project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

permalink: pretty

url: https://credittools.org

aux_links:
  "Custom Styles":
    - "/assets/custom-styles.css"

collections:
  cards:
    output: true

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag