title: New Project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://samsunggalaxyplayer.github.io/new-project

aux_links:
  Subreddit: https://reddit.com

collections:
  businesses:
    output: true