title: New Project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

permalink: pretty

url: https://samsunggalaxyplayer.github.io/new-project

aux_links:
  Propose Change: https://github.com

collections:
  businesses:
    output: true

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag