title: CreditTools.org
description: CreditTools.org is a not-for-profit website that aims to educate individuals on good credit card and other financial habits. It aims to be the definitive free resource on credit cards.
theme: just-the-docs

permalink: pretty

url: https://credittools.org

aux_links:
  Propose Change: https://github.com

collections:
  cards:
    output: true

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag

# Optional callouts. To use: {: .warning } before paragraph
callouts:
  warning:
    title: Warning
    color: red
  friendly:
    color: blue

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_cards"
      type: "cards"
    values:
      layout: "default"
